version: 2

project_name: git-clean

before:
  hooks:
    - cargo fetch --locked

builds:
  - id: git-clean
    builder: rust
    binary: git-clean
    flags:
      - --release
      - --locked
    targets:
      - x86_64-unknown-linux-gnu
      - aarch64-unknown-linux-gnu
      - x86_64-apple-darwin
      - aarch64-apple-darwin
      - x86_64-pc-windows-gnu

archives:
  - id: binaries
    builds:
      - git-clean
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

brews:
  - name: git-clean
    repository:
      owner: aaronflorey
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/aaronflorey/git-clean"
    description: "Clean stale Git branches safely"
